name: "Podcast RSS Feed Generator"
author: "Nangjang"
description: "Generates a feed for a podcast from a YAML file"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.email }}
    - ${{ inputs.name }}
branding:
  icon: "git-branch"
  color: "green"
inputs:
  email:
    description: "The committer's email address"
    required: true
    default: "${{ github.actor }}@localhost"
  name:
    description: "The committer's name"
    required: true
    default: "${{ github.actor }}"
